import '../styles/globals.css';
import {AppProps} from "next/app";
import Head from "next/head";
import React from "react";
import { Noto_Sans } from 'next/font/google';

const notSans = Noto_Sans({
    subsets: ['latin'],
    weight: ['300', '400', '500', '700']
});

export default function App({ Component, pageProps }: AppProps): JSX.Element {
    return <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <style>
                {`
                    html {
                        font-family: ${notSans.style.fontFamily};
                    }        
                `}
            </style>
        </Head>
        <Component {...pageProps} />
    </>;
}